### ISSUE TITLE
Multiple CrashLoopBackoffs related to db migration

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/metadata#138]
/kind bug

**What steps did you take and what happened:**
Deploy Kubeflow using the metadata package from manifests.
The image tag is: `v0.1.9`.

20 minutes after deploying, all servers  were in CrashLoopBackoff.
The logs seemed related to a migration:

```text
F1015 10:54:29.242102       1 main.go:90] Failed to create ML Metadata Store with config mysql:<host:"metadata-db.kubeflow" port:3306 database:"metadb" user:"root" password:"test" > : mysql_query failed: errno: 1054, error: Unknown column 'is_artifact_type' in '
Type'
        Failed to migrate existing db; the migration transaction rolls back..
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc0001ec300, 0xc0001f6000, 0x153, 0x1a9)
        external/com_github_golang_glog/glog.go:769 +0xb1
github.com/golang/glog.(*loggingT).output(0x16ba6c0, 0xc000000003, 0xc000032070, 0x156222b, 0x7, 0x5a, 0x0)
        external/com_github_golang_glog/glog.go:720 +0x2f6
github.com/golang/glog.(*loggingT).printf(0x16ba6c0, 0x3, 0xfd0bfa, 0x37, 0xc0001bde30, 0x2, 0x2)
        external/com_github_golang_glog/glog.go:655 +0x14e
github.com/golang/glog.Fatalf(...)
        external/com_github_golang_glog/glog.go:1148
main.mlmdStoreOrDie(0x0)
        server/main.go:90 +0x1c3
main.main()
        server/main.go:101 +0xe0
```

Issue remains even after deleting and recreating all the Pods.

**What did you expect to happen:**
I expected Pods to become Ready without any restarts.

**Environment:**

- Metadata version: v0.1.9
- Kubeflow version: v0.7.0-rc1
- Kubernetes version: (use `kubectl version`): 1.14
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by zhenghuiwang** [comment]
/cc @dushyanthsc @neuromage 

I think it is related to the MLMD upgrade in https://github.com/kubeflow/metadata/pull/130

@yanniszark  does the database `metadb` exist before this installation or not?

**Comment by yanniszark** [comment]
@zhenghuiwang it was a brand new GKE cluster.
Nothing should have been there.

/priority p0
/cc @jlewi

**Comment by neuromage** [comment]
@yanniszark This is due to db upgrade as pointed out by @zhenghuiwang. Is it reproducible if you drop the databases manually? 

@zhenghuiwang Since #130 went in, did we update the API server backend?

**Comment by neuromage** [comment]
> @zhenghuiwang Since #130 went in, did we update the API server backend?

I mean did we upgrade the image? Is 0.1.9 using the older version? That's what it sounds like to me looking at the error.

**Comment by zhenghuiwang** [comment]
I deployed the v0.7-rc following [the demo script](https://docs.google.com/document/d/1OhjKwas74OOFwiADQfNzakgopoAxgNzD3bERdO1cGt8/edit#heading=h.ycyohiypkfa6). (The demo script deploys Kubeflow using the Kubeflow/Manifest master HEAD, which includes [the PR of reducing #replicas of metadata service to 2](https://github.com/kubeflow/manifests/pull/531))

**What I found**
- The service `metadata-service` and `metadata-grpc-service` can start and function after each replica restarts around 3 times.
- Some of the restarts are due to the `medata-db` service is not available.
- I only found two error logs are about the `Failed to create ML Metadata Store..... error: Unknown column 'is_artifact_type' in 'Type'`. One in a pod of `metadata-deployment and one in a pod of `metadata-grpc-deployment`. (See them in the error logs section)

**Suspected root cause**
I guess the error message `Failed to migrate existing db; the migration transaction rolls back.MetadataStore cannot be created with the given connection config.` is not really about migration but about DB table creation.

I saw two such messages in both the gRPC service log and http service log. Because there are exactly two messages, I guess what was happening is there is a contention among these server instances to init the DB tables during startup: Two concurrent transactions of initializing DB were aborted and the next transaction after them passed.

@yanniszark  I think you see more restarts because there used to be 6 servers instead of 4. Hence more contention.

**What to do**
Ideally these retries of table creation transactions should be handled in the program instead of relying on the container recreation. But I don't think it is a serious problem now since the deployment of the component is fast with 4 replicas (there are couple of restarts because of dependency not ready). 

@yanniszark would you retry deploying the v07rc1 and see if it works for you now?

**Error Logs**
- metadata gRPC service
```
  
2019-10-15 14:40:38.839 PDT
2019-10-15 21:40:38.839499: F ml_metadata/metadata_store/metadata_store_server_main.cc:178] Non-OK-status: ml_metadata::CreateMetadataStore(connection_config, &metadata_store) status: Internal: mysql_real_connect failed: errno: 2002, error: Can't connect to MySQL server on 'metadata-db.kubeflow' (115)MetadataStore cannot be created with the given connection config.

2019-10-15 14:40:54.163 PDT
2019-10-15 21:40:54.163543: F ml_metadata/metadata_store/metadata_store_server_main.cc:178] Non-OK-status: ml_metadata::CreateMetadataStore(connection_config, &metadata_store) status: Internal: mysql_real_connect failed: errno: 2002, error: Can't connect to MySQL server on 'metadata-db.kubeflow' (115)MetadataStore cannot be created with the given connection config.

2019-10-15 14:41:19.437 PDT
2019-10-15 21:41:19.436611: F ml_metadata/metadata_store/metadata_store_server_main.cc:178] Non-OK-status: ml_metadata::CreateMetadataStore(connection_config, &metadata_store) status: Internal: mysql_query failed: errno: 1062, error: Duplicate entry '0' for key 'PRIMARY'

2019-10-15 14:41:19.437 PDT
Failed to migrate existing db; the migration transaction rolls back.MetadataStore cannot be created with the given connection config.

2019-10-15 14:41:20.149 PDT
2019-10-15 21:41:20.149475: F ml_metadata/metadata_store/metadata_store_server_main.cc:178] Non-OK-status: ml_metadata::CreateMetadataStore(connection_config, &metadata_store) status: Internal: mysql_query failed: errno: 1062, error: Duplicate entry '4' for key 'PRIMARY'MetadataStore cannot be created with the given connection config.

2019-10-15 14:41:51.248 PDT
2019-10-15 21:41:51.248238: I ml_metadata/metadata_store/metadata_store_server_main.cc:197] 
 ```

- metadata service
```
F 2019-10-15T21:40:35.896551Z Failed to create ML Metadata Store with config mysql:<host:"metadata-db.kubeflow" port:3306 database:"metadb" user:"root" password:"test" > : mysql_real_connect failed: errno: 2002, error: Can't connect to MySQL server on 'metadata-db.kubeflow' (115). 

F 2019-10-15T21:40:53.459614Z Failed to create ML Metadata Store with config mysql:<host:"metadata-db.kubeflow" port:3306 database:"metadb" user:"root" password:"test" > : mysql_real_connect failed: errno: 2002, error: Can't connect to MySQL server on 'metadata-db.kubeflow' (115). 

F 2019-10-15T21:41:19.467823Z Failed to create ML Metadata Store with config mysql:<host:"metadata-db.kubeflow" port:3306 database:"metadb" user:"root" password:"test" > : mysql_query failed: errno: 1054, error: Unknown column 'is_artifact_type' in 'Type' 
E 2019-10-15T21:41:19.468294900Z 	Failed to migrate existing db; the migration transaction rolls back..
```

**Comment by amygdala** [comment]
Just as a data point -- in my kf07 install, they don't seem to be recovering. (thus far they've crashed 23 times)

**Comment by jeffgriffith** [comment]
@zhenghuiwang would this merge of a retry fix the case where this never recovers? i see a fresh rc8 cluster for me has metadata-deployment/grpc restarting 290+ times with the last error still being the same as above (Unknown column 'is_artifact_type'):
```
F1105 17:04:52.446574       1 main.go:90] Failed to create ML Metadata Store with config mysql:<host:"metadata-db.kubeflow" port:3306 database:"metadb" user:"root" password:"test" > : mysql_query failed: errno: 1054, error: Unknown column 'is_artifact_type' in 'Type'
        Failed to migrate existing db; the migration transaction rolls back..

```

**Comment by parthmishra** [comment]
Had the same issue with 0.7.0 (official release) and was only able to resolve by running `kfctl delete --delete_storage` and then redeploying. Deleting the pods didn't help.

**Comment by zhenghuiwang** [comment]
@jeffgriffith @parthmishra Sorry for this problem. I'm still trying to figure out a resolution.

Here is a workaround that only reinstalls the metadata component:

1. Download the kubeflow/manifest
`git clone https://github.com/kubeflow/manifests`
`cd manifests/metadata/base`

2. Delete kubeflow metadata with [kustomize](https://github.com/kubernetes-sigs/kustomize):
`kustomize build . | kubectl delete -n kubeflow -f `

3. Reinstall it
`kustomize build . | kubectl apply -n kubeflow -f `

**Comment by zhenghuiwang** [comment]
This issue is due to a data race problem during table schema initialization&upgrade inside MLMD. (A more detailed report will be added)

The current best workaround is still the one described above.

**Comment by jlewi** [comment]
@jtfogarty this looks like an issue with metadata 
engprod = Engineering Productivity and usually refers to CI/CD for Kubeflow

/area metadata

@zhenghuiwang it looks like a number of PRs were merged. Is this still an issue?

**Comment by zhenghuiwang** [comment]
The issue was fixed in MLMD 0.15.1 image.
